version: "3.3"

services:
  server:
    image: nginx:alpine
    volumes:
      - ../public:/usr/share/nginx/html
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - links
    ports:
      - 8001:80

networks:
  links:
