version: "3.3"

services:
  server:
    image: node:alpine
    user: node
    working_dir: /home/node/public
    command: npx live-server
    ports:
      - 8080:8080
    volumes:
      - ../public:/home/node/public
    networks:
      - links

networks:
  links:
