name: Delivery workflow

on:
  push:
    branches:
    - prototype

jobs:
  docker-build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: joaorodriguesjr
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      uses: docker/build-push-action@v2
      with:
        file: docker/dockerfile
        context: .
        tags: ghcr.io/joaorodriguesjr/links:${{ github.sha }}
        push: true

    - name: Apply
      run: |
        sed 's#CONTAINER_IMAGE#ghcr.io/joaorodriguesjr/links:${{ github.sha }}#' kubernetes/deployment.yml | microk8s.kubectl apply -f -
        microk8s.kubectl apply -f kubernetes/service.yml
        microk8s.kubectl apply -f kubernetes/ingress.yml

    - name: Rollout
      run: |
        microk8s.kubectl rollout restart deployment.apps/links
