name: deployment workflow

on:
  push:
    tags:
    - '*'

jobs:
  deployment:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Revision
      run: |
        sed -i 's#REVISION_HASH#${{ github.ref_name }}#' public/index.html

    - name: Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: joaorodriguesjr
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      uses: docker/build-push-action@v2
      with:
        file: docker/dockerfile
        context: .
        tags: ghcr.io/joaorodriguesjr/links:${{ github.ref_name }}
        push: true

    - name: Apply
      run: |
        sed -i 's#CONTAINER_IMAGE#ghcr.io/joaorodriguesjr/links:${{ github.ref_name }}#' kubernetes/deployment.yml
        microk8s.kubectl apply -f kubernetes/deployment.yml
        microk8s.kubectl apply -f kubernetes/service.yml
        microk8s.kubectl apply -f kubernetes/ingress.yml

    - name: Rollout
      run: |
        microk8s.kubectl rollout restart deployment.apps/links
